---
title: "data_process"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data_process}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(polypharmacy)
```

# Speed Test
Using dataset [prescriptions.rds](https://github.com/guiboucher/polypharmacy/blob/master/data-fake/prescriptions.rds).
```{r, echo=FALSE}
library(parallel)
library(microbenchmark)
Rx_deliv <- readRDS("E:/Github/polypharmacy/data-fake/prescriptions.rds")
str(Rx_deliv)
dp_core <- function(n) {
  return(data_process(
    Rx_deliv, "ID", "Code", "Date", "Duree",
    Cohort = NULL, Cohort_id = NULL,
    Hosp_stays = NULL, Hosp_id = NULL, Hosp_admis = NULL, Hosp_discharge = NULL,
    study_start = NULL, study_end = NULL,
    grace_fctr = 0.5, grace_cst = 0, max_reserve = NULL,
    cores = n
  ))
}
```
```{r}
microbenchmark(dp_core(1), dp_core(2), dp_core(3), dp_core(4),
               dp_core(5), dp_core(6), dp_core(7), dp_core(8),
               dp_core(9), dp_core(10), dp_core(11), dp_core(12),
               dp_core(13), dp_core(14), dp_core(15), dp_core(16))
```

